services:
  db:
    image: scylladb/scylla:latest
    environment:
      POSTGRES_DB: broker
    healthcheck:
      test: [ "CMD", "cqlsh", "-e 'DESCRIBE broker;'" ]
      interval: 30s
      timeout: 10s
      retries: 5
#    command: ["/bin/sh", "-c", "sleep 30 && echo initializing db && cqlsh -f /docker-entrypoint-initdb.d/initdb.cql"] # TODO fix
    volumes:
      - ./initdb.cql:/docker-entrypoint-initdb.d/initdb.cql
  broker:
    image: message_broker:v1
    build:
      context: .
      target: release
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 50051:50051
    env_file:
      - config.env
  prometheus:
    image: prom/prometheus
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000