global:
  scrape_interval: 1s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: broker
    static_configs:
      - targets: [ "broker:8080" ]
  - job_name: grafana
    static_configs:
      - targets: [ "grafana:3000" ]
